### ISSUE TITLE
md5_client -L info crashes in SSL_CIPHER_get_id

### ISSUE THREAD

**Issue by kenstir** [litespeedtech/lsquic#298]
md5_client crashes below `print_conn_info` because there is no cipher established yet (SSL_get_current_cipher returns NULL).

Stack:
```
Core was generated by `md5_client -L debug -H kcx7.vivox.com -f id_jenkins.pub'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004eb608 in SSL_CIPHER_get_id (cipher=0x0)
    at /home/kenstir/src/lsquic.boringssl/ssl/ssl_cipher.cc:1369
1369	uint32_t SSL_CIPHER_get_id(const SSL_CIPHER *cipher) { return cipher->id; }
Missing separate debuginfos, use: debuginfo-install libevent-2.0.21-4.el7.x86_64
(gdb) bt
#0  0x00000000004eb608 in SSL_CIPHER_get_id (cipher=0x0)
    at /home/kenstir/src/lsquic.boringssl/ssl/ssl_cipher.cc:1369
#1  0x000000000041e7b2 in iquic_esf_keysize (enc_session_p=0xd6c010)
    at /home/kenstir/src/lsquic/src/liblsquic/lsquic_enc_sess_ietf.c:2571
#2  0x000000000041e83f in iquic_esf_alg_keysize (enc_session_p=0xd6c010)
    at /home/kenstir/src/lsquic/src/liblsquic/lsquic_enc_sess_ietf.c:2598
#3  0x000000000041728b in lsquic_conn_crypto_alg_keysize (lconn=0xd680c0)
    at /home/kenstir/src/lsquic/src/liblsquic/lsquic_conn.c:125
#4  0x00000000004164b1 in print_conn_info (conn=0xd680c0) at /home/kenstir/src/lsquic/bin/test_common.c:2216
#5  0x000000000040fd53 in client_on_new_conn (stream_if_ctx=0x7ffc12aaed90, conn=0xd680c0)
    at /home/kenstir/src/lsquic/bin/md5_client.c:95
#6  0x0000000000442e3e in ietf_full_conn_ci_client_call_on_new (lconn=0xd680c0)
    at /home/kenstir/src/lsquic/src/liblsquic/lsquic_full_conn_ietf.c:2921
#7  0x000000000042515d in lsquic_engine_connect (engine=0xd27250, version=N_LSQVER, local_sa=0xd20298, 
    peer_sa=0xd20218, peer_ctx=0xd20180, conn_ctx=0x0, hostname=0x7ffc12ab1549 "kcx7.vivox.com", base_plpmtu=0, 
    sess_resume=0x0, sess_resume_len=0, token=0x0, token_sz=0)
    at /home/kenstir/src/lsquic/src/liblsquic/lsquic_engine.c:1820
#8  0x000000000041175e in prog_connect (prog=0x7ffc12aaedd0, sess_resume=0x0, sess_resume_len=0)
    at /home/kenstir/src/lsquic/bin/prog.c:397
#9  0x0000000000410d19 in main (argc=7, argv=0x7ffc12aaf338) at /home/kenstir/src/lsquic/bin/md5_client.c:515
(gdb) 
```

**Comment by kenstir** [comment]
PR incoming
